<?php
//Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
  exit;
}

?>

<ul class="sbv-country-lists-ul">
  <li id="AF">Afghanistan</li>
	<li id="AX">Åland Islands</li>
	<li id="AL">Albania</li>
	<li id="DZ">Algeria</li>
	<li id="AS">American Samoa</li>
	<li id="AD">Andorra</li>
	<li id="AO">Angola</li>
	<li id="AI">Anguilla</li>
	<li id="AQ">Antarctica</li>
	<li id="AG">Antigua and Barbuda</li>
	<li id="AR">Argentina</li>
	<li id="AM">Armenia</li>
	<li id="AW">Aruba</li>
	<li id="AU">Australia</li>
	<li id="AT">Austria</li>
	<li id="AZ">Azerbaijan</li>
	<li id="BS">Bahamas</li>
	<li id="BH">Bahrain</li>
	<li id="BD">Bangladesh</li>
	<li id="BB">Barbados</li>
	<li id="BY">Belarus</li>
	<li id="BE">Belgium</li>
	<li id="BZ">Belize</li>
	<li id="BJ">Benin</li>
	<li id="BM">Bermuda</li>
	<li id="BT">Bhutan</li>
	<li id="BO">Bolivia, Plurinational State of</li>
	<li id="BQ">Bonaire, Sint Eustatius and Saba</li>
	<li id="BA">Bosnia and Herzegovina</li>
	<li id="BW">Botswana</li>
	<li id="BV">Bouvet Island</li>
	<li id="BR">Brazil</li>
	<li id="IO">British Indian Ocean Territory</li>
	<li id="BN">Brunei Darussalam</li>
	<li id="BG">Bulgaria</li>
	<li id="BF">Burkina Faso</li>
	<li id="BI">Burundi</li>
	<li id="KH">Cambodia</li>
	<li id="CM">Cameroon</li>
	<li id="CA">Canada</li>
	<li id="CV">Cape Verde</li>
	<li id="KY">Cayman Islands</li>
	<li id="CF">Central African Republic</li>
	<li id="TD">Chad</li>
	<li id="CL">Chile</li>
	<li id="CN">China</li>
	<li id="CX">Christmas Island</li>
	<li id="CC">Cocos (Keeling) Islands</li>
	<li id="CO">Colombia</li>
	<li id="KM">Comoros</li>
	<li id="CG">Congo</li>
	<li id="CD">Congo, the Democratic Republic of the</li>
	<li id="CK">Cook Islands</li>
	<li id="CR">Costa Rica</li>
	<li id="CI">Côte d'Ivoire</li>
	<li id="HR">Croatia</li>
	<li id="CU">Cuba</li>
	<li id="CW">Curaçao</li>
	<li id="CY">Cyprus</li>
	<li id="CZ">Czech Republic</li>
	<li id="DK">Denmark</li>
	<li id="DJ">Djibouti</li>
	<li id="DM">Dominica</li>
	<li id="DO">Dominican Republic</li>
	<li id="EC">Ecuador</li>
	<li id="EG">Egypt</li>
	<li id="SV">El Salvador</li>
	<li id="GQ">Equatorial Guinea</li>
	<li id="ER">Eritrea</li>
	<li id="EE">Estonia</li>
	<li id="ET">Ethiopia</li>
	<li id="FK">Falkland Islands (Malvinas)</li>
	<li id="FO">Faroe Islands</li>
	<li id="FJ">Fiji</li>
	<li id="FI">Finland</li>
	<li id="FR">France</li>
	<li id="GF">French Guiana</li>
	<li id="PF">French Polynesia</li>
	<li id="TF">French Southern Territories</li>
	<li id="GA">Gabon</li>
	<li id="GM">Gambia</li>
	<li id="GE">Georgia</li>
	<li id="DE">Germany</li>
	<li id="GH">Ghana</li>
	<li id="GI">Gibraltar</li>
	<li id="GR">Greece</li>
	<li id="GL">Greenland</li>
	<li id="GD">Grenada</li>
	<li id="GP">Guadeloupe</li>
	<li id="GU">Guam</li>
	<li id="GT">Guatemala</li>
	<li id="GG">Guernsey</li>
	<li id="GN">Guinea</li>
	<li id="GW">Guinea-Bissau</li>
	<li id="GY">Guyana</li>
	<li id="HT">Haiti</li>
	<li id="HM">Heard Island and McDonald Islands</li>
	<li id="VA">Holy See (Vatican City State)</li>
	<li id="HN">Honduras</li>
	<li id="HK">Hong Kong</li>
	<li id="HU">Hungary</li>
	<li id="IS">Iceland</li>
	<li id="IN">India</li>
	<li id="ID">Indonesia</li>
	<li id="IR">Iran, Islamic Republic of</li>
	<li id="IQ">Iraq</li>
	<li id="IE">Ireland</li>
	<li id="IM">Isle of Man</li>
	<li id="IL">Israel</li>
	<li id="IT">Italy</li>
	<li id="JM">Jamaica</li>
	<li id="JP">Japan</li>
	<li id="JE">Jersey</li>
	<li id="JO">Jordan</li>
	<li id="KZ">Kazakhstan</li>
	<li id="KE">Kenya</li>
	<li id="KI">Kiribati</li>
	<li id="KP">Korea, Democratic People's Republic of</li>
	<li id="KR">Korea, Republic of</li>
	<li id="KW">Kuwait</li>
	<li id="KG">Kyrgyzstan</li>
	<li id="LA">Lao People's Democratic Republic</li>
	<li id="LV">Latvia</li>
	<li id="LB">Lebanon</li>
	<li id="LS">Lesotho</li>
	<li id="LR">Liberia</li>
	<li id="LY">Libya</li>
	<li id="LI">Liechtenstein</li>
	<li id="LT">Lithuania</li>
	<li id="LU">Luxembourg</li>
	<li id="MO">Macao</li>
	<li id="MK">Macedonia, the former Yugoslav Republic of</li>
	<li id="MG">Madagascar</li>
	<li id="MW">Malawi</li>
	<li id="MY">Malaysia</li>
	<li id="MV">Maldives</li>
	<li id="ML">Mali</li>
	<li id="MT">Malta</li>
	<li id="MH">Marshall Islands</li>
	<li id="MQ">Martinique</li>
	<li id="MR">Mauritania</li>
	<li id="MU">Mauritius</li>
	<li id="YT">Mayotte</li>
	<li id="MX">Mexico</li>
	<li id="FM">Micronesia, Federated States of</li>
	<li id="MD">Moldova, Republic of</li>
	<li id="MC">Monaco</li>
	<li id="MN">Mongolia</li>
	<li id="ME">Montenegro</li>
	<li id="MS">Montserrat</li>
	<li id="MA">Morocco</li>
	<li id="MZ">Mozambique</li>
	<li id="MM">Myanmar</li>
	<li id="NA">Namibia</li>
	<li id="NR">Nauru</li>
	<li id="NP">Nepal</li>
	<li id="NL">Netherlands</li>
	<li id="NC">New Caledonia</li>
	<li id="NZ">New Zealand</li>
	<li id="NI">Nicaragua</li>
	<li id="NE">Niger</li>
	<li id="NG">Nigeria</li>
	<li id="NU">Niue</li>
	<li id="NF">Norfolk Island</li>
	<li id="MP">Northern Mariana Islands</li>
	<li id="NO">Norway</li>
	<li id="OM">Oman</li>
	<li id="PK">Pakistan</li>
	<li id="PW">Palau</li>
	<li id="PS">Palestinian Territory, Occupied</li>
	<li id="PA">Panama</li>
	<li id="PG">Papua New Guinea</li>
	<li id="PY">Paraguay</li>
	<li id="PE">Peru</li>
	<li id="PH">Philippines</li>
	<li id="PN">Pitcairn</li>
	<li id="PL">Poland</li>
	<li id="PT">Portugal</li>
	<li id="PR">Puerto Rico</li>
	<li id="QA">Qatar</li>
	<li id="RE">Réunion</li>
	<li id="RO">Romania</li>
	<li id="RU">Russian Federation</li>
	<li id="RW">Rwanda</li>
	<li id="BL">Saint Barthélemy</li>
	<li id="SH">Saint Helena, Ascension and Tristan da Cunha</li>
	<li id="KN">Saint Kitts and Nevis</li>
	<li id="LC">Saint Lucia</li>
	<li id="MF">Saint Martin (French part)</li>
	<li id="PM">Saint Pierre and Miquelon</li>
	<li id="VC">Saint Vincent and the Grenadines</li>
	<li id="WS">Samoa</li>
	<li id="SM">San Marino</li>
	<li id="ST">Sao Tome and Principe</li>
	<li id="SA">Saudi Arabia</li>
	<li id="SN">Senegal</li>
	<li id="RS">Serbia</li>
	<li id="SC">Seychelles</li>
	<li id="SL">Sierra Leone</li>
	<li id="SG">Singapore</li>
	<li id="SX">Sint Maarten (Dutch part)</li>
	<li id="SK">Slovakia</li>
	<li id="SI">Slovenia</li>
	<li id="SB">Solomon Islands</li>
	<li id="SO">Somalia</li>
	<li id="ZA">South Africa</li>
	<li id="GS">South Georgia and the South Sandwich Islands</li>
	<li id="SS">South Sudan</li>
	<li id="ES">Spain</li>
	<li id="LK">Sri Lanka</li>
	<li id="SD">Sudan</li>
	<li id="SR">Suriname</li>
	<li id="SJ">Svalbard and Jan Mayen</li>
	<li id="SZ">Swaziland</li>
	<li id="SE">Sweden</li>
	<li id="CH">Switzerland</li>
	<li id="SY">Syrian Arab Republic</li>
	<li id="TW">Taiwan, Province of China</li>
	<li id="TJ">Tajikistan</li>
	<li id="TZ">Tanzania, United Republic of</li>
	<li id="TH">Thailand</li>
	<li id="TL">Timor-Leste</li>
	<li id="TG">Togo</li>
	<li id="TK">Tokelau</li>
	<li id="TO">Tonga</li>
	<li id="TT">Trinidad and Tobago</li>
	<li id="TN">Tunisia</li>
	<li id="TR">Turkey</li>
	<li id="TM">Turkmenistan</li>
	<li id="TC">Turks and Caicos Islands</li>
	<li id="TV">Tuvalu</li>
	<li id="UG">Uganda</li>
	<li id="UA">Ukraine</li>
	<li id="AE">United Arab Emirates</li>
	<li id="GB">United Kingdom</li>
	<li id="US">United States</li>
	<li id="UM">United States Minor Outlying Islands</li>
	<li id="UY">Uruguay</li>
	<li id="UZ">Uzbekistan</li>
	<li id="VU">Vanuatu</li>
	<li id="VE">Venezuela, Bolivarian Republic of</li>
	<li id="VN">Viet Nam</li>
	<li id="VG">Virgin Islands, British</li>
	<li id="VI">Virgin Islands, U.S.</li>
	<li id="WF">Wallis and Futuna</li>
	<li id="EH">Western Sahara</li>
	<li id="YE">Yemen</li>
	<li id="ZM">Zambia</li>
	<li id="ZW">Zimbabwe</li>
</ul>

<script type="text/javascript">
  var sbv_country = '';
  var sbv_country_code = '';

  jQuery(".sbv-country-lists-ul li").each(function(i) {

    jQuery(this).on("click", function() {
      sbv_country = jQuery(this).html();
      sbv_country_code = jQuery(this).attr("id");

      jQuery(".sbv-country-lists-ul li").css({
        "background-color": "transparent",
        "color": "#000"
      });

      jQuery(this).css({
        "background-color": "blue",
        "color": "#fff"
      });
    });
  });
</script>
